name: Daily Python Script

on:
  schedule:
    - cron: '0 0 * * *' # runs everyday at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Run Python script
      run: summary.py